import test from 'node:test';
import { createServer } from 'node:http';
import { sampleOutput } from '../enrich/helpers.mjs';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { bootServer, findChrome, launchChrome, startFakeImmich } from './harness.mjs';

test('Settings manages profiles; Enrich links to profiles and saved run settings, preserves selection, pins queue revisions, and runs without losing history', { timeout: 60000 }, async t => {
  if (!findChrome()) return t.skip('Chrome required');
  const dir = mkdtempSync(join(tmpdir(), 'pictaria-profile-browser-'));
  let server, browser, immich, model, finishModelRequest, signalModelRequest;
  const modelRequestStarted = new Promise(resolve => { signalModelRequest = resolve; });
  t.after(async () => {
    finishModelRequest?.();
    await Promise.allSettled([browser?.stop(), server?.stop(), immich?.stop()]);
    if (model) await new Promise(resolve => model.close(resolve));
    rmSync(dir, { recursive: true, force: true });
  });
  const asset = { id: '00000000-0000-0000-0000-000000000001', type: 'IMAGE', originalFileName: 'test.jpg',
    localDateTime: '2026-01-01T12:00:00Z', exifInfo: { city: 'Paris' } };
  immich = await startFakeImmich({ assets: [asset], serveAssetDetails: true });
  model = createServer((request, response) => {
    request.resume(); request.on('end', () => {
      finishModelRequest = () => {
        response.writeHead(200, { 'Content-Type': 'application/json' });
        response.end(JSON.stringify({ choices: [{ message: { content: JSON.stringify(sampleOutput()) } }] }));
        finishModelRequest = null;
      };
      signalModelRequest();
    });
  });
  await new Promise(resolve => model.listen(0, '127.0.0.1', resolve));
  server = await bootServer(dir, { env: { ENRICH_ENABLED: 'true', DEFAULT_PROVIDER: 'local_lmstudio', IMMICH_BASE_URL: immich.base, IMMICH_API_KEY: 'fake-key', LMSTUDIO_BASE_URL: `http://127.0.0.1:${model.address().port}/v1`, LMSTUDIO_MODEL: 'test' } });
  assert.equal((await fetch(`${server.base}/api/enrich/profiles`)).status, 401);
  browser = await launchChrome(); const page = await browser.newPage();
  await page.navigate(`${server.base}/enrich.html`);
  await page.waitFor('document.querySelector(".gate-backdrop input")');
  await page.evaluate('document.querySelector(".gate-backdrop input").value = "smoke-secret"; document.querySelector(".gate-backdrop button").click()');
  await page.waitFor('document.querySelector("#enrichProfile option") && !document.querySelector(".gate-backdrop")');
  const legacyPatch = await page.evaluate("fetch('/api/settings', { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({enrich:{systemPrompt:'Obsolete'}})}).then(async r=>({status:r.status,body:await r.json()}))");
  assert.equal(legacyPatch.status, 400); assert.match(legacyPatch.body.error.message, /profiles/);
  const invalidProfile = await page.evaluate("fetch('/api/enrich/prompts?profileId=missing').then(r=>r.status)");
  assert.equal(invalidProfile, 400);
  const click = id => page.evaluate(`document.getElementById(${JSON.stringify(id)}).click()`);
  const fill = (id, value) => page.evaluate(`document.getElementById(${JSON.stringify(id)}).value = ${JSON.stringify(value)}; document.getElementById(${JSON.stringify(id)}).dispatchEvent(new Event("input", {bubbles:true}))`);
  const follow = async id => page.navigate(await page.evaluate(`document.getElementById(${JSON.stringify(id)}).href`));
  assert.equal(await page.evaluate('document.querySelector("#profileEditor, #profileNew, #profileArchive")'), null);
  assert.equal(await page.evaluate('document.querySelector("#taxPanel, #profileView, #profileEdit")'), null);
  assert.equal(await page.evaluate('document.getElementById("profileManage").textContent'), 'View and manage profiles');
  assert.equal(await page.evaluate('document.getElementById("viewConfigurationBtn").hidden'), true);
  await follow('profileManage');
  await page.waitFor('document.getElementById("sec-enrichment-profiles")?.open && document.querySelector("#profileList .profile-row")');
  assert.equal(await page.evaluate('document.getElementById("profileEditor").hidden'), true);
  const backToList = async () => {
    await click('profileBack');
    await page.waitFor('!document.getElementById("profileLibrary").hidden && !document.getElementById("profileListControls").disabled');
  };
  const rowAction = async (action, id) => {
    await page.evaluate(`(() => { const button = document.querySelector('[data-action="${action}"][data-profile-id="${id}"]'); const menu = button.closest('.profile-menu'); if (menu) menu.open = true; button.click(); })()`);
  };
  const initialId = await page.evaluate('document.querySelector("#profileList .profile-row").dataset.profileId');
  await rowAction('edit', initialId);
  await page.waitFor('!document.getElementById("profileEditor").hidden && !document.getElementById("profileEditorControls").disabled');
  assert.equal(await page.evaluate('document.getElementById("profileLibrary").hidden'), true);
  assert.equal(await page.evaluate('document.getElementById("profileTaxonomyDetails").open'), false);
  assert.match(await page.evaluate('document.getElementById("profileTaxonomySummary").textContent'), /tags in .* categories/);
  // Cancel preserves a draft unless the user explicitly discards it.
  await fill('profileName', 'Unsaved name'); await click('profileClose');
  await page.waitFor('document.getElementById("profileDiscardDialog").open');
  await click('profileKeepEditing');
  await page.waitFor('!document.getElementById("profileEditorControls").disabled');
  assert.equal(await page.evaluate('document.getElementById("profileName").value'), 'Unsaved name');
  assert.match(await page.evaluate('document.getElementById("profileDirty").textContent'), /Unsaved/);
  // Leaving through navigation asks too; keeping the draft stays on Settings.
  await page.evaluate('Array.from(document.querySelectorAll(".p-nav a")).find(a => a.pathname === "/enrich.html").click()');
  await page.waitFor('document.getElementById("profileDiscardDialog").open');
  await click('profileKeepEditing');
  assert.equal(await page.evaluate('location.pathname'), '/settings.html');
  assert.equal(await page.evaluate('(() => { const event = new Event("beforeunload", {cancelable:true}); window.dispatchEvent(event); return event.defaultPrevented; })()'), true);

  await click('profileClose'); await page.waitFor('document.getElementById("profileDiscardDialog").open');
  await click('profileDiscard');
  await page.waitFor('!document.getElementById("profileLibrary").hidden && !document.getElementById("profileListControls").disabled');
  await rowAction('duplicate', initialId);
  await page.waitFor('!document.getElementById("profileCreate").hidden');
  assert.equal(await page.evaluate('document.getElementById("profileSource").value'), initialId);
  await click('profileCreateContinue');
  await page.waitFor('!document.getElementById("profileEditor").hidden && !document.getElementById("profileEditorControls").disabled');
  await fill('profileName', 'Travel <test>'); await fill('profileUser', 'Invalid template'); await click('profileSave');
  await page.waitFor('document.getElementById("profileUserError").textContent.includes("approved_tags")');
  assert.equal(await page.evaluate('document.querySelectorAll("#profileList .profile-row").length'), 1);
  await fill('profileUser', 'Travel tags: {approved_tags}');
  const taxonomy = await page.evaluate('document.getElementById("profileTaxonomy").value');
  await fill('profileTaxonomy', '{}'); await click('profileSave');
  await page.waitFor('document.getElementById("profileTaxonomyError").textContent && !document.getElementById("profileEditorControls").disabled');
  assert.equal(await page.evaluate('document.getElementById("profileTaxonomyDetails").open'), true);
  assert.equal(await page.evaluate('document.activeElement.id'), 'profileTaxonomy');
  await fill('profileTaxonomy', taxonomy); await click('profileValidate');
  await page.waitFor('document.getElementById("profileEditorNote").textContent.includes("valid.")');
  await click('profileSave'); await page.waitFor('document.getElementById("profileEditorNote").textContent.includes("Saved Travel") && !document.getElementById("profileEditorControls").disabled');
  const profileId = await page.evaluate('new URL(document.getElementById("profileReturn").href).searchParams.get("profile")');
  const queued = await page.evaluate(`fetch('/api/enrich/queue', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({title:'Travel queue', filters:{day:'2026-01-01'}, profileId:${JSON.stringify(profileId)}})}).then(r=>r.json())`);
  assert.ok(queued.id);
  await fill('profileSystem', 'New revision system prompt'); await click('profileSave');
  await page.waitFor('document.getElementById("profileDirty").textContent.includes("revision 2") && !document.getElementById("profileEditorControls").disabled');
  await follow('profileReturn');
  await page.waitFor('document.querySelector("#queueList .queue-profile")');
  assert.equal(await page.evaluate('document.getElementById("enrichProfile").value'), profileId);
  assert.match(await page.evaluate('document.getElementById("queueList").textContent'), /Travel <test> · r1/);
  await page.evaluate('document.querySelector("#queueList .queue-profile").click()');
  await page.waitFor('document.getElementById("queueList").textContent.includes("Travel <test> · r2")');
  // Real browser → HTTP → Immich/provider adapters → SQLite run.
  await page.evaluate('document.querySelector("#queueList .p-btn.accent").click()');
  await modelRequestStarted;
  await page.waitFor('document.getElementById("viewConfigurationBtn").textContent === "View run settings" && !document.getElementById("viewConfigurationBtn").hidden');
  await click('viewConfigurationBtn');
  await page.waitFor('!document.getElementById("logPopup").hidden');
  assert.equal(await page.evaluate('document.getElementById("logPopupTitle").textContent'), 'Current run settings');
  assert.match(await page.evaluate('document.getElementById("logPopupMeta").textContent'), /Travel <test> · r2/);
  assert.match(await page.evaluate('document.getElementById("logPopupBody").textContent'), /New revision system prompt/);
  assert.equal(await page.evaluate('document.getElementById("runSettingsTechnical").open'), false);
  assert.match(await page.evaluate('document.getElementById("runSettingsIdentifiers").textContent'), /Configuration: [a-f0-9]{64}/);
  assert.doesNotMatch(await page.evaluate('document.getElementById("logPopupBody").textContent'), /Configuration: [a-f0-9]{64}/);
  await click('logPopupClose');
  await click('viewLogBtn');
  assert.equal(await page.evaluate('document.getElementById("runSettingsTechnical").hidden'), true);
  await click('logPopupClose');
  finishModelRequest();
  await page.waitFor('document.querySelector("#runsList .run-configuration")');
  assert.match(await page.evaluate('document.getElementById("runsList").textContent'), /Travel <test> · r2/);
  const runs = await page.evaluate("fetch('/api/enrich/runs').then(r=>r.json())");
  assert.equal(runs.runs[0].status, 'finished');
  assert.equal(runs.runs[0].counters.succeeded, 1);
  await page.waitFor('document.getElementById("viewConfigurationBtn").textContent === "View last run settings"');
  await click('viewConfigurationBtn'); await page.waitFor('!document.getElementById("logPopup").hidden');
  assert.equal(await page.evaluate('document.getElementById("logPopupTitle").textContent'), 'Last run settings');
  await click('logPopupClose');
  assert.equal(await page.evaluate('document.querySelector("#runsList .run-configuration").textContent'), 'View run settings');
  await page.evaluate('document.querySelector("#runsList .run-configuration").click()');
  await page.waitFor('!document.getElementById("logPopup").hidden');
  assert.equal(await page.evaluate('document.getElementById("logPopupTitle").textContent'), 'Run settings');
  await click('logPopupClose');
  await follow('profileManage');
  await page.waitFor('document.querySelector("#profileList .profile-row")');
  assert.equal(await page.evaluate('document.getElementById("profileEditor").hidden'), true);
  await rowAction('edit', profileId);
  await page.waitFor('document.getElementById("profileSystem")?.value === "New revision system prompt"');
  assert.equal(await page.evaluate('new URL(location.href).searchParams.get("profile")'), profileId);
  assert.match(await page.evaluate('document.getElementById("profileEditorTitle").textContent'), /Edit Travel <test>/);
  await backToList();
  await rowAction('archive', profileId);
  await page.waitFor('document.querySelectorAll("#profileList .profile-row").length === 1 && !document.getElementById("profileListControls").disabled');
  await page.evaluate('document.getElementById("profileArchivedSection").open = true');
  await rowAction('restore', profileId);
  await page.waitFor('document.querySelectorAll("#profileList .profile-row").length === 2 && !document.getElementById("profileListControls").disabled');
  await rowAction('default', profileId);
  await page.waitFor('document.getElementById("profileNote").textContent.startsWith("Travel <test> is used") && !document.getElementById("profileListControls").disabled');
  await click('profileNew'); await page.waitFor('!document.getElementById("profileCreate").hidden');
  await fill('profileCreateName', 'Built-in restored');
  assert.equal(await page.evaluate('document.getElementById("profileSource").value'), '');
  await click('profileCreateContinue');
  await page.waitFor('!document.getElementById("profileEditor").hidden && !document.getElementById("profileEditorControls").disabled');
  await click('profileSave');
  await page.waitFor('document.getElementById("profileEditorNote").textContent.includes("Saved Built-in") && !document.getElementById("profileEditorControls").disabled');
  // A save from another tab must not overwrite this draft or be overwritten by it.
  const builtinId = await page.evaluate('new URL(document.getElementById("profileReturn").href).searchParams.get("profile")');
  await page.evaluate(`(async () => {
    const profile = await fetch('/api/enrich/profiles/${builtinId}').then(r => r.json());
    const response = await fetch('/api/enrich/profiles/${builtinId}', {method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({...profile, systemPrompt:'Saved in another tab', expectedRevisionId:profile.revisionId})});
    if (!response.ok) throw new Error('Concurrent edit failed');
  })()`);
  await fill('profileSystem', 'My unsaved draft'); await click('profileSave');
  await page.waitFor('document.getElementById("profileEditorNote").textContent.includes("another window") && !document.getElementById("profileEditorControls").disabled');
  assert.equal(await page.evaluate('document.getElementById("profileSystem").value'), 'My unsaved draft');
  assert.match(await page.evaluate('document.getElementById("profileDirty").textContent'), /Unsaved/);
  await click('profileClose'); await page.waitFor('document.getElementById("profileDiscardDialog").open');
  await click('profileDiscard');
  await page.waitFor('!document.getElementById("profileLibrary").hidden && !document.getElementById("profileListControls").disabled');
  await rowAction('edit', builtinId);
  await page.waitFor('!document.getElementById("profileEditor").hidden && !document.getElementById("profileEditorControls").disabled');
  assert.equal(await page.evaluate('document.getElementById("profileSystem").value'), 'Saved in another tab');
  // Plain text rendering and a narrow viewport protect against prompt/name markup and overflow.
  assert.equal(await page.evaluate('document.querySelectorAll("#sec-enrichment-profiles test").length'), 0);
  await page.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  assert.equal(await page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), true);
  if (process.env.PICTARIA_PROFILE_SCREENSHOT) {
    const shot = await page.send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: true });
    writeFileSync(process.env.PICTARIA_PROFILE_SCREENSHOT, Buffer.from(shot.data, 'base64'));
  }
  await follow('profileReturn');
  await page.waitFor('document.querySelector("#runsList .run-configuration")');
  assert.match(await page.evaluate('document.getElementById("runsList").textContent'), /Travel <test> · r2/);
  assert.equal(await page.evaluate('document.querySelectorAll("#profilePanel test, #runsList test").length'), 0);
  assert.equal(await page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), true);
  // A stale edit link must not silently open the default profile for editing.
  await page.navigate(`${server.base}/settings.html?profile=missing#sec-enrichment-profiles`);
  await page.waitFor('document.getElementById("profileStatus")?.textContent.includes("unavailable")');
  assert.equal(await page.evaluate('document.getElementById("profileEditor").hidden'), true);
});
